org.gradle.jvmargs=-Xmx4096m
org.gradle.configureondemand=false
org.gradle.parallel=true

kotlin.code.style=official

kotlin.mpp.stability.nowarn=true
kotlin.js.yarn=false

android.useAndroidX=true

moko.publish.name=MOKO graphics
moko.publish.description=Graphics primitives for mobile (android & ios) Kotlin Multiplatform development
moko.publish.repo.org=icerockdev
moko.publish.repo.name=moko-graphics
moko.publish.license=Apache-2.0
moko.publish.developers=Alex009|Aleksey Mikhailov|aleksey.mikhailov@icerockdev.com,nrobi144|Nagy Robert|nagyrobi144@gmail.com
